src/Presentation/Nl.Web/Areas/Admin/Controllers/ReturnRequestController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Nl.Core.Domain.Orders;
using Nl.Services.Customers;
using Nl.Services.Localization;
using Nl.Services.Logging;
using Nl.Services.Messages;
using Nl.Services.Orders;
using Nl.Services.Security;
using Nl.Web.Areas.Admin.Factories;
using Nl.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nl.Web.Areas.Admin.Models.Orders;
using Nl.WebFramework.Controllers;
using Nl.WebFramework.Mvc.Filters;

namespace Nl.Web.Areas.Admin.Controllers
{
    public partial class ReturnRequestController : BaseAdminController
    {
        #region Fields

        private readonly ICustomerActivityService _customerActivityService;
        private readonly ICustomerService _customerService;
        private readonly ILocalizationService _localizationService;
        private readonly ILocalizedEntityService _localizedEntityService;
        private readonly INotificationService _notificationService;
        private readonly IOrderService _orderService;
        private readonly IPermissionService _permissionService;
        private readonly IReturnRequestModelFactory _returnRequestModelFactory;
        private readonly IReturnRequestService _returnRequestService;
        private readonly IWorkflowMessageService _workflowMessageService;

        #endregion Fields

        #region Ctor

        public ReturnRequestController(ICustomerActivityService customerActivityService,
            ICustomerService customerService,
            ILocalizationService localizationService,
            ILocalizedEntityService localizedEntityService,
            INotificationService notificationService,
            IOrderService orderService,
            IPermissionService permissionService,
            IReturnRequestModelFactory returnRequestModelFactory,
            IReturnRequestService returnRequestService,
            IWorkflowMessageService workflowMessageService)
        {
            _customerActivityService = customerActivityService;
            _customerService = customerService;
            _localizationService = localizationService;
            _localizedEntityService = localizedEntityService;
            _notificationService = notificationService;
            _orderService = orderService;
            _permissionService = permissionService;
            _returnRequestModelFactory = returnRequestModelFactory;
            _returnRequestService = returnRequestService;
            _workflowMessageService = workflowMessageService;
        }

        #endregion

        #region Utilities

        protected virtual void UpdateLocales(ReturnRequestReason rrr, ReturnRequestReasonModel model)
        {
            foreach (var localized in model.Locales)
            {
                _localizedEntityService.SaveLocalizedValue(rrr,
                    x => x.Name,
                    localized.Name,
                    localized.LanguageId);
            }
        }

        protected virtual void UpdateLocales(ReturnRequestAction rra, ReturnRequestActionModel model)
        {
            foreach (var localized in model.Locales)
            {
                _localizedEntityService.SaveLocalizedValue(rra,
                    x => x.Name,
                    localized.Name,
                    localized.LanguageId);
            }
        }

        #endregion

        #region Methods

        public virtual IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public virtual IActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageReturnRequests))
                return AccessDeniedView();

            //prepare model
            var model = _returnRequestModelFactory.PrepareReturnRequestSearchModel(new ReturnRequestSearchModel());

            return View(model);
        }

        [HttpPost]
        public virtual IActionResult List(ReturnRequestSearchModel searchModel)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageReturnRequests))
                return AccessDeniedKendoGridJson();

            //prepare model
            var model = _returnRequestModelFactory.PrepareReturnRequestListModel(searchModel);

            return Json(model);
        }

        public virtual IActionResult Edit(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageReturnRequests))
                return AccessDeniedView();

            //try to get a return request with the specified id
            var returnRequest = _returnRequestService.GetReturnRequestById(id);
            if (returnRequest == null)
                return RedirectToAction("List");

            //prepare model
            var model = _returnRequestModelFactory.PrepareReturnRequestModel(null, returnRequest);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        [FormValueRequired("save", "save-continue")]
        public virtual IActionResult Edit(ReturnRequestModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageReturnRequests))
                return AccessDeniedView();

            //try to get a return request with the specified id
            var returnRequest = _returnRequestService.GetReturnRequestById(model.Id);
            if (returnRequest == null)
                return RedirectToAction("List");

            if (ModelState.IsValid)
            {
                returnRequest = model.ToEntity(returnRequest);
                returnRequest.UpdatedOnUtc = DateTime.UtcNow;
                _customerService.UpdateCustomer(returnRequest.Customer);

                //activity log
                _customerActivityService.InsertActivity("EditReturnRequest",
                    string.Format(_localizationService.GetResource("ActivityLog.EditReturnRequest"), returnRequest.Id), returnRequest);

                _notificationService.SuccessNotification(_localizationService.GetResource("Admin.ReturnRequests.Updated"));

                return continueEditing ? RedirectToAction("Edit", new { id = returnRequest.Id }) : RedirectToAction("List");
            }

            //prepare model
            model = _returnRequestModelFactory.PrepareReturnRequestModel(model, returnRequest, true);

            //if we got this far, something failed, redisplay form
            return View(model);
        }

        [HttpPost, ActionName("Edit")]
        [FormValueRequired("notify-customer")]
        public virtual IActionResult NotifyCustomer(ReturnRequestModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageReturnRequests))
                return AccessDeniedView();

            //try to get a return request with the specified id
            var returnRequest = _returnRequestService.GetReturnRequestById(model.Id);
            if (returnRequest == null)
                return RedirectToAction("List");

            var orderItem = _orderService.GetOrderItemById(returnRequest.OrderItemId);
            if (orderItem == null)
            {
                _notificationService.ErrorNotification(_localizationService.GetResource("Admin.ReturnRequests.OrderItemDeleted"));
                return RedirectToAction("Edit", new { id = returnRequest.Id });
            }

            var queuedEmailIds = _workflowMessageService.SendReturnRequestStatusChangedCustomerNotification(returnRequest, orderItem, orderItem.Order.CustomerLanguageId);
            if (queuedEmailIds.Any())
                _notificationService.SuccessNotification(_localizationService.GetResource("Admin.ReturnRequests.Notified"));

            return RedirectToAction("Edit", new { id = returnRequest.Id });
        }

        [HttpPost]
        public virtual IActionResult Delete(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageReturnRequests))
                return AccessDeniedView();

            //try to get a return request with the specified id
            var returnRequest = _returnRequestService.GetReturnRequestById(id);
            if (returnRequest == null)
                return RedirectToAction("List");

            _returnRequestService.DeleteReturnRequest(returnRequest);

            //activity log
            _customerActivityService.InsertActivity("DeleteReturnRequest",
                string.Format(_localizationService.GetResource("ActivityLog.DeleteReturnRequest"), returnRequest.Id), returnRequest);

            _notificationService.SuccessNotification(_localizationService.GetResource("Admin.ReturnRequests.Deleted"));

            return RedirectToAction("List");
        }

        #region Return request reasons

        public virtual IActionResult ReturnRequestReasonList()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            //select "return request" tab
            SaveSelectedTabName("tab-returnrequest");

            //we just redirect a user to the order settings page
            return RedirectToAction("Order", "Setting");
        }

        [HttpPost]
        public virtual IActionResult ReturnRequestReasonList(ReturnRequestReasonSearchModel searchModel)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSettings))
                return AccessDeniedKendoGridJson();

            //prepare model
            var model = _returnRequestModelFactory.PrepareReturnRequestReasonListModel(searchModel);

            return Json(model);
        }

        public virtual IActionResult ReturnRequestReasonCreate()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageSettings))
                return AccessDeniedView();

            //prepare model

src/Presentation/Nl.Web/Areas/Admin/Views/ReturnRequest/Edit.cshtml
@model ReturnRequestModel

@{
    //page title
    ViewBag.Title = T("Admin.ReturnRequests.EditReturnRequestDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Return requests");
}

<form asp-controller="ReturnRequest" asp-action="Edit" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.ReturnRequests.EditReturnRequestDetails")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.ReturnRequests.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="notify-customer" class="btn bg-aqua">
                <i class="fa fa-envelope-o"></i>
                @T("Admin.ReturnRequests.NotifyCustomer")
            </button>
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="returnrequest-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ReturnRequestDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="returnrequest-delete" />

src/Presentation/Nl.Web/Areas/Admin/Views/ReturnRequest/List.cshtml
@model ReturnRequestSearchModel

@{
    //page title
    ViewBag.Title = T("Admin.ReturnRequests").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Return requests");
}

<nop-antiforgery-token />
<div class="content-header clearfix">
    <h1 class="pull-left">
        @T("Admin.ReturnRequests")
    </h1>
    <div class="pull-right">
        &nbsp;
        @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ReturnRequestListButtons })
    </div>
</div>
<div class="content">
    <div class="form-horizontal">
        <div class="panel-group">
            <div class="panel panel-default panel-search">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="col-md-4">
                                    <nop-label asp-for="CustomNumber" />
                                </div>
                                <div class="col-md-8">
                                    <nop-editor asp-for="CustomNumber" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-4">
                                    <nop-label asp-for="StartDate" />
                                </div>
                                <div class="col-md-8">
                                    <nop-editor asp-for="StartDate" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-4">
                                    <nop-label asp-for="EndDate" />
                                </div>
                                <div class="col-md-8">
                                    <nop-editor asp-for="EndDate" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-4">
                                    <nop-label asp-for="ReturnRequestStatusId" />
                                </div>
                                <div class="col-md-8">
                                    <nop-select asp-for="ReturnRequestStatusId" asp-items="Model.ReturnRequestStatusList" />
                                </div>
                            </div>

                            <div class="col-md-8 col-md-offset-4">
                                <button type="button" id="search-returnrequests" class="btn btn-primary btn-search">
                                    <i class="fa fa-search"></i>
                                    @T("Admin.Common.Search")
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-body">
                    <p>
                        @T("Admin.ReturnRequests.Description")
                    </p>
                    <div id="returnrequests-grid"></div>

                    <script>
                        $(document)
                            .ready(function() {
                                $("#returnrequests-grid")
                                    .kendoGrid({
                                        dataSource: {
                                            type: "json",
                                            transport: {
                                                read: {
                                                    url: "@Html.Raw(Url.Action("List", "ReturnRequest"))",
                                                    type: "POST",
                                                    dataType: "json",
                                                    data: function() {
                                                        var data = {
                                                            StartDate: $('#@Html.IdFor(model => model.StartDate)').val(),
                                                            EndDate: $('#@Html.IdFor(model => model.EndDate)').val(),
                                                            CustomNumber: $('#@Html.IdFor(model => model.CustomNumber)').val(),
                                                            ReturnRequestStatusId: $('#@Html.IdFor(model => model.ReturnRequestStatusId)').val()
                                                        };
                                                        addAntiForgeryToken(data);
                                                        return data;
                                                    }
                                                }
                                            },
                                            schema: {
                                                data: "Data",
                                                total: "Total",
                                                errors: "Errors"
                                            },
                                            error: function(e) {
                                                display_kendoui_grid_error(e);
                                                // Cancel the changes
                                                this.cancelChanges();
                                            },
                                            pageSize: @(Model.PageSize),
                                            serverPaging: true,
                                            serverFiltering: true,
                                            serverSorting: true
                                        },
                                        pageable: {
                                            refresh: true,
                                            pageSizes: [@(Model.AvailablePageSizes)],
                                            @await Html.PartialAsync("_GridPagerMessages")
                                        },
                                        editable: {
                                            confirmation: "@T("Admin.Common.DeleteConfirmation")",
                                            mode: "inline"
                                        },
                                        scrollable: false,
                                        columns: [
                                            {
                                                field: "CustomNumber",
                                                title: "@T("Admin.ReturnRequests.Fields.CustomNumber")",
                                                width: 100
                                            }, {
                                                field: "ProductName",
                                                title: "@T("Admin.ReturnRequests.Fields.Product")",
                                                width: 350,
                                                template:
                                                    '# if(ProductId > 0) {# <a href="@Url.Content("~/Admin/Product/Edit/")#=ProductId#">#:ProductName#</a> ' +
                                                        '# if(AttributeInfo && AttributeInfo.length > 0) {# <div>#=AttributeInfo#</div> #} # #} else {# order item is deleted #} #'
                                            }, {
                                                field: "Quantity",
                                                title: "@T("Admin.ReturnRequests.Fields.Quantity")",
                                                width: 100
                                            }, {
                                                field: "CustomerId",
                                                title: "@T("Admin.ReturnRequests.Fields.Customer")",
                                                width: 200,
                                                template:
                                                    '<a href="@Url.Content("~/Admin/Customer/Edit/")#=CustomerId#">#:CustomerInfo#</a>'
                                            }, {
                                                field: "CustomOrderNumber",
                                                title: "@T("Admin.ReturnRequests.Fields.CustomOrderNumber")",
                                                width: 200,
                                                headerAttributes: { style: "text-align:center" },
                                                attributes: { style: "text-align:center" },
                                                template: '# if(OrderId > 0) {# <a class="btn btn-default" href="@Url.Content("~/Admin/Order/Edit/")#=OrderId#"><i class="fa fa-eye"></i>#=CustomOrderNumber# - @T("Admin.Common.View")</a> #} else {# order item is deleted #} #'
                                            }, {
                                                field: "ReturnRequestStatusStr",
                                                title: "@T("Admin.ReturnRequests.Fields.Status")",
                                                width: 100
                                            }, {
                                                field: "CreatedOn",
                                                title: "@T("Admin.ReturnRequests.Fields.CreatedOn")",
                                                width: 100,
                                                type: "date",
                                                format: "{0:G}"
                                            }, {
                                                field: "Id",
                                                title: "@T("Admin.Common.Edit")",
                                                width: 100,
                                                headerAttributes: { style: "text-align:center" },
                                                attributes: { style: "text-align:center" },
                                                template: '<a class="btn btn-default" href="Edit/#=Id#"><i class="fa fa-pencil"></i>@T("Admin.Common.Edit")</a>'
                                            }
                                        ]
                                    });
                            });
                    </script>

                    <script>
                        $(document)
                        .ready(function() {
                            $('#search-returnrequests')
                                .click(function() {
                                    var grid = $('#returnrequests-grid').data('kendoGrid');
                                    grid.dataSource.page(1); //new search. Set page size to 1
                                    //grid.dataSource.read(); we already loaded the grid above using "page" function
                                    return false;
                                });
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>

src/Presentation/Nl.Web/Areas/Admin/Views/ReturnRequest/ReturnRequestActionCreate.cshtml
@model ReturnRequestActionModel

@{
    //page title
    ViewBag.Title = T("Admin.Configuration.Settings.Order.ReturnRequestActions.AddNew").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Order settings");
}

<form asp-controller="ReturnRequest" asp-action="ReturnRequestActionCreate" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Configuration.Settings.Order.ReturnRequestActions.AddNew")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="ReturnRequestActionList">@T("Admin.Configuration.Settings.Order.ReturnRequestActions.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ReturnRequestActionDetailsButtons })
        </div>
    </div>

    <div class="content">
        <div class="form-horizontal">
            @await Html.PartialAsync("_CreateOrUpdate.ReturnRequestAction", Model)
        </div>
    </div>
</form>

src/Presentation/Nl.Web/Areas/Admin/Views/ReturnRequest/ReturnRequestActionEdit.cshtml
@model ReturnRequestActionModel

@{
    //page title
    ViewBag.Title = T("Admin.Configuration.Settings.Order.ReturnRequestActions.EditDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Order settings");
}


<form asp-controller="ReturnRequest" asp-action="ReturnRequestActionEdit" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Configuration.Settings.Order.ReturnRequestActions.EditDetails") - @Model.Name
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="ReturnRequestActionList">@T("Admin.Configuration.Settings.Order.ReturnRequestActions.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="returnrequestaction-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ReturnRequestActionDetailsButtons, additionalData = Model })
        </div>
    </div>

    <div class="content">
        <div class="form-horizontal">
            @await Html.PartialAsync("_CreateOrUpdate.ReturnRequestAction", Model)
        </div>
    </div>
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="returnrequestaction-delete" asp-action="ReturnRequestActionDelete"/>

src/Presentation/Nl.Web/Areas/Admin/Views/ReturnRequest/ReturnRequestReasonCreate.cshtml
@model ReturnRequestReasonModel

@{
    //page title
    ViewBag.Title = T("Admin.Configuration.Settings.Order.ReturnRequestReasons.AddNew").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Order settings");
}


<form asp-controller="ReturnRequest" asp-action="ReturnRequestReasonCreate" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Configuration.Settings.Order.ReturnRequestReasons.AddNew")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="ReturnRequestReasonList">@T("Admin.Configuration.Settings.Order.ReturnRequestReasons.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ReturnRequestReasonDetailsButtons })
        </div>
    </div>

    <div class="content">
        <div class="form-horizontal">
            @await Html.PartialAsync("_CreateOrUpdate.ReturnRequestReason", Model)
        </div>
    </div>
</form>

src/Presentation/Nl.Web/Areas/Admin/Views/ReturnRequest/ReturnRequestReasonEdit.cshtml
@model ReturnRequestReasonModel

@{
    //page title
    ViewBag.Title = T("Admin.Configuration.Settings.Order.ReturnRequestReasons.EditDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Order settings");
}

<form asp-controller="ReturnRequest" asp-action="ReturnRequestReasonEdit" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Configuration.Settings.Order.ReturnRequestReasons.EditDetails") - @Model.Name
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="ReturnRequestReasonList">@T("Admin.Configuration.Settings.Order.ReturnRequestReasons.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="returnrequestreason-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ReturnRequestReasonDetailsButtons, additionalData = Model })
        </div>
    </div>

    <div class="content">
        <div class="form-horizontal">
            @await Html.PartialAsync("_CreateOrUpdate.ReturnRequestReason", Model)
        </div>
    </div>
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="returnrequestreason-delete" asp-action="ReturnRequestReasonDelete"/>